package net.shoreline.client.init;

import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;
import net.shoreline.client.ShorelineMod;
import net.shoreline.client.api.module.Module;
import net.shoreline.client.api.module.ToggleModule;
import net.shoreline.client.impl.module.client.BaritoneModule;
import net.shoreline.client.impl.module.client.CapesModule;
import net.shoreline.client.impl.module.client.ClickGuiModule;
import net.shoreline.client.impl.module.client.ColorsModule;
import net.shoreline.client.impl.module.client.HUDModule;
import net.shoreline.client.impl.module.client.RotationsModule;
import net.shoreline.client.impl.module.client.ServerModule;
import net.shoreline.client.impl.module.combat.AuraModule;
import net.shoreline.client.impl.module.combat.AutoArmorModule;
import net.shoreline.client.impl.module.combat.AutoBowReleaseModule;
import net.shoreline.client.impl.module.combat.AutoCrystalModule;
import net.shoreline.client.impl.module.combat.AutoLogModule;
import net.shoreline.client.impl.module.combat.AutoTotemModule;
import net.shoreline.client.impl.module.combat.AutoTrapModule;
import net.shoreline.client.impl.module.combat.AutoWebModule;
import net.shoreline.client.impl.module.combat.AutoXPModule;
import net.shoreline.client.impl.module.combat.BackTrackModule;
import net.shoreline.client.impl.module.combat.BlockLagModule;
import net.shoreline.client.impl.module.combat.BowAimModule;
import net.shoreline.client.impl.module.combat.ClickCrystalModule;
import net.shoreline.client.impl.module.combat.CriticalsModule;
import net.shoreline.client.impl.module.combat.HoleFillModule;
import net.shoreline.client.impl.module.combat.NoHitDelayModule;
import net.shoreline.client.impl.module.combat.ReplenishModule;
import net.shoreline.client.impl.module.combat.SelfBowModule;
import net.shoreline.client.impl.module.combat.SelfTrapModule;
import net.shoreline.client.impl.module.combat.SurroundModule;
import net.shoreline.client.impl.module.combat.TriggerModule;
import net.shoreline.client.impl.module.exploit.AntiHungerModule;
import net.shoreline.client.impl.module.exploit.ChorusControlModule;
import net.shoreline.client.impl.module.exploit.ClientSpoofModule;
import net.shoreline.client.impl.module.exploit.CrasherModule;
import net.shoreline.client.impl.module.exploit.DisablerModule;
import net.shoreline.client.impl.module.exploit.ExtendedFireworkModule;
import net.shoreline.client.impl.module.exploit.FakeLatencyModule;
import net.shoreline.client.impl.module.exploit.FastLatencyModule;
import net.shoreline.client.impl.module.exploit.FastProjectileModule;
import net.shoreline.client.impl.module.exploit.PacketCancelerModule;
import net.shoreline.client.impl.module.exploit.PacketFlyModule;
import net.shoreline.client.impl.module.exploit.PhaseModule;
import net.shoreline.client.impl.module.exploit.PortalGodModeModule;
import net.shoreline.client.impl.module.exploit.ReachModule;
import net.shoreline.client.impl.module.misc.AntiAimModule;
import net.shoreline.client.impl.module.misc.AntiSpamModule;
import net.shoreline.client.impl.module.misc.AutoAcceptModule;
import net.shoreline.client.impl.module.misc.AutoEatModule;
import net.shoreline.client.impl.module.misc.AutoFishModule;
import net.shoreline.client.impl.module.misc.AutoReconnectModule;
import net.shoreline.client.impl.module.misc.AutoRespawnModule;
import net.shoreline.client.impl.module.misc.BeaconSelectorModule;
import net.shoreline.client.impl.module.misc.BetterChatModule;
import net.shoreline.client.impl.module.misc.ChatNotifierModule;
import net.shoreline.client.impl.module.misc.ChestSwapModule;
import net.shoreline.client.impl.module.misc.FakePlayerModule;
import net.shoreline.client.impl.module.misc.InvCleanerModule;
import net.shoreline.client.impl.module.misc.MiddleClickModule;
import net.shoreline.client.impl.module.misc.NoPacketKickModule;
import net.shoreline.client.impl.module.misc.NoSoundLagModule;
import net.shoreline.client.impl.module.misc.PacketLoggerModule;
import net.shoreline.client.impl.module.misc.TimerModule;
import net.shoreline.client.impl.module.misc.TrueDurabilityModule;
import net.shoreline.client.impl.module.misc.UnfocusedFPSModule;
import net.shoreline.client.impl.module.misc.XCarryModule;
import net.shoreline.client.impl.module.movement.AntiLevitationModule;
import net.shoreline.client.impl.module.movement.AutoWalkModule;
import net.shoreline.client.impl.module.movement.ElytraFlyModule;
import net.shoreline.client.impl.module.movement.EntityControlModule;
import net.shoreline.client.impl.module.movement.EntitySpeedModule;
import net.shoreline.client.impl.module.movement.FakeLagModule;
import net.shoreline.client.impl.module.movement.FastFallModule;
import net.shoreline.client.impl.module.movement.FlightModule;
import net.shoreline.client.impl.module.movement.IceSpeedModule;
import net.shoreline.client.impl.module.movement.JesusModule;
import net.shoreline.client.impl.module.movement.LongJumpModule;
import net.shoreline.client.impl.module.movement.NoFallModule;
import net.shoreline.client.impl.module.movement.NoJumpDelayModule;
import net.shoreline.client.impl.module.movement.NoSlowModule;
import net.shoreline.client.impl.module.movement.ParkourModule;
import net.shoreline.client.impl.module.movement.SpeedModule;
import net.shoreline.client.impl.module.movement.SprintModule;
import net.shoreline.client.impl.module.movement.StepModule;
import net.shoreline.client.impl.module.movement.TickShiftModule;
import net.shoreline.client.impl.module.movement.TridentFlyModule;
import net.shoreline.client.impl.module.movement.VelocityModule;
import net.shoreline.client.impl.module.movement.YawModule;
import net.shoreline.client.impl.module.render.BlockHighlightModule;
import net.shoreline.client.impl.module.render.BreadcrumbsModule;
import net.shoreline.client.impl.module.render.BreakHighlightModule;
import net.shoreline.client.impl.module.render.ChamsModule;
import net.shoreline.client.impl.module.render.ESPModule;
import net.shoreline.client.impl.module.render.ExtraTabModule;
import net.shoreline.client.impl.module.render.FreecamModule;
import net.shoreline.client.impl.module.render.FullbrightModule;
import net.shoreline.client.impl.module.render.HoleESPModule;
import net.shoreline.client.impl.module.render.NameProtectModule;
import net.shoreline.client.impl.module.render.NametagsModule;
import net.shoreline.client.impl.module.render.NoRenderModule;
import net.shoreline.client.impl.module.render.NoRotateModule;
import net.shoreline.client.impl.module.render.NoWeatherModule;
import net.shoreline.client.impl.module.render.ParticlesModule;
import net.shoreline.client.impl.module.render.PhaseESPModule;
import net.shoreline.client.impl.module.render.SkeletonModule;
import net.shoreline.client.impl.module.render.SkyboxModule;
import net.shoreline.client.impl.module.render.TooltipsModule;
import net.shoreline.client.impl.module.render.TracersModule;
import net.shoreline.client.impl.module.render.TrueSightModule;
import net.shoreline.client.impl.module.render.ViewClipModule;
import net.shoreline.client.impl.module.render.ViewModelModule;
import net.shoreline.client.impl.module.world.AntiInteractModule;
import net.shoreline.client.impl.module.world.AutoMineModule;
import net.shoreline.client.impl.module.world.AutoToolModule;
import net.shoreline.client.impl.module.world.AvoidModule;
import net.shoreline.client.impl.module.world.BlockInteractModule;
import net.shoreline.client.impl.module.world.FastDropModule;
import net.shoreline.client.impl.module.world.FastPlaceModule;
import net.shoreline.client.impl.module.world.MultitaskModule;
import net.shoreline.client.impl.module.world.NoGlitchBlocksModule;
import net.shoreline.client.impl.module.world.ScaffoldModule;
import net.shoreline.client.impl.module.world.SpeedmineModule;

public class Modules {
   public static ServerModule SERVER;
   public static ClickGuiModule CLICK_GUI;
   public static ColorsModule COLORS;
   public static HUDModule HUD;
   public static RotationsModule ROTATIONS;
   public static BaritoneModule BARITONE;
   public static CapesModule CAPES;
   public static AuraModule AURA;
   public static AutoArmorModule AUTO_ARMOR;
   public static AutoBowReleaseModule AUTO_BOW_RELEASE;
   public static AutoCrystalModule AUTO_CRYSTAL;
   public static AutoLogModule AUTO_LOG;
   public static AutoTotemModule AUTO_TOTEM;
   public static AutoTrapModule AUTO_TRAP;
   public static AutoWebModule AUTO_WEB;
   public static AutoXPModule AUTO_XP;
   public static BackTrackModule BACK_TRACK;
   public static BlockLagModule BLOCK_LAG;
   public static BowAimModule BOW_AIM;
   public static ClickCrystalModule CLICK_CRYSTAL;
   public static CriticalsModule CRITICALS;
   public static HoleFillModule HOLE_FILL;
   public static NoHitDelayModule NO_HIT_DELAY;
   public static ReplenishModule REPLENISH;
   public static SelfBowModule SELF_BOW;
   public static SelfTrapModule SELF_TRAP;
   public static SurroundModule SURROUND;
   public static TriggerModule TRIGGER;
   public static AntiHungerModule ANTI_HUNGER;
   public static ChorusControlModule CHORUS_CONTROL;
   public static ClientSpoofModule CLIENT_SPOOFER;
   public static CrasherModule CRASHER;
   public static DisablerModule DISABLER;
   public static ExtendedFireworkModule EXTENDED_FIREWORK;
   public static FakeLatencyModule FAKE_LATENCY;
   public static FastLatencyModule FAST_LATENCY;
   public static FastProjectileModule FAST_PROJECTILE;
   public static PacketCancelerModule PACKET_CANCELER;
   public static PacketFlyModule PACKET_FLY;
   public static PhaseModule PHASE;
   public static PortalGodModeModule PORTAL_GOD_MODE;
   public static ReachModule REACH;
   public static AntiAimModule ANTI_AIM;
   public static NoPacketKickModule ANTI_BOOK_BAN;
   public static AntiSpamModule ANTI_SPAM;
   public static AutoAcceptModule AUTO_ACCEPT;
   public static AutoEatModule AUTO_EAT;
   public static AutoFishModule AUTO_FISH;
   public static AutoReconnectModule AUTO_RECONNECT;
   public static AutoRespawnModule AUTO_RESPAWN;
   public static BeaconSelectorModule BEACON_SELECTOR;
   public static BetterChatModule BETTER_CHAT;
   public static ChatNotifierModule CHAT_NOTIFIER;
   public static ChestSwapModule CHEST_SWAP;
   public static FakePlayerModule FAKE_PLAYER;
   public static InvCleanerModule INV_CLEANER;
   public static MiddleClickModule MIDDLE_CLICK;
   public static NoPacketKickModule NO_PACKET_KICK;
   public static NoSoundLagModule NO_SOUND_LAG;
   public static PacketLoggerModule PACKET_LOGGER;
   public static TimerModule TIMER;
   public static TrueDurabilityModule TRUE_DURABILITY;
   public static UnfocusedFPSModule UNFOCUSED_FPS;
   public static XCarryModule XCARRY;
   public static AntiLevitationModule ANTI_LEVITATION;
   public static AutoWalkModule AUTO_WALK;
   public static ElytraFlyModule ELYTRA_FLY;
   public static EntityControlModule ENTITY_CONTROL;
   public static EntitySpeedModule ENTITY_SPEED;
   public static FakeLagModule FAKE_LAG;
   public static FastFallModule FAST_FALL;
   public static FlightModule FLIGHT;
   public static IceSpeedModule ICE_SPEED;
   public static JesusModule JESUS;
   public static LongJumpModule LONG_JUMP;
   public static NoFallModule NO_FALL;
   public static NoJumpDelayModule NO_JUMP_DELAY;
   public static NoSlowModule NO_SLOW;
   public static ParkourModule PARKOUR;
   public static SpeedModule SPEED;
   public static SprintModule SPRINT;
   public static StepModule STEP;
   public static TickShiftModule TICK_SHIFT;
   public static TridentFlyModule TRIDENT_FLY;
   public static VelocityModule VELOCITY;
   public static YawModule YAW;
   public static BlockHighlightModule BLOCK_HIGHLIGHT;
   public static BreadcrumbsModule BREADCRUMBS;
   public static BreakHighlightModule BREAK_HIGHLIGHT;
   public static ChamsModule CHAMS;
   public static ESPModule ESP;
   public static ExtraTabModule EXTRA_TAB;
   public static FreecamModule FREECAM;
   public static FullbrightModule FULLBRIGHT;
   public static NameProtectModule NAME_PROTECT;
   public static HoleESPModule HOLE_ESP;
   public static NametagsModule NAMETAGS;
   public static NoRenderModule NO_RENDER;
   public static NoRotateModule NO_ROTATE;
   public static NoWeatherModule NO_WEATHER;
   public static ParticlesModule PARTICLES;
   public static PhaseESPModule PHASE_ESP;
   public static SkeletonModule SKELETON;
   public static SkyboxModule SKYBOX;
   public static TooltipsModule TOOLTIPS;
   public static TracersModule TRACERS;
   public static TrueSightModule TRUE_SIGHT;
   public static ViewClipModule VIEW_CLIP;
   public static ViewModelModule VIEW_MODEL;
   public static AntiInteractModule ANTI_INTERACT;
   public static AutoMineModule AUTO_MINE;
   public static AutoToolModule AUTO_TOOL;
   public static AvoidModule AVOID;
   public static BlockInteractModule BLOCK_INTERACT;
   public static FastDropModule FAST_DROP;
   public static FastPlaceModule FAST_PLACE;
   public static MultitaskModule MULTITASK;
   public static NoGlitchBlocksModule NO_GLITCH_BLOCKS;
   public static ScaffoldModule SCAFFOLD;
   public static SpeedmineModule SPEEDMINE;
   private static boolean initialized;
   private static Set<Module> CACHE;

   private static Module getRegisteredModule(String id) {
      Module registered = Managers.MODULE.getModule(id);
      if (CACHE.add(registered)) {
         return registered;
      } else {
         throw new IllegalStateException("Invalid module requested: " + id);
      }
   }

   public static void init() {
      if (Managers.isInitialized()) {
         CACHE = new HashSet();
         CLICK_GUI = (ClickGuiModule)getRegisteredModule("clickgui-module");
         COLORS = (ColorsModule)getRegisteredModule("colors-module");
         HUD = (HUDModule)getRegisteredModule("hud-module");
         ROTATIONS = (RotationsModule)getRegisteredModule("rotations-module");
         SERVER = (ServerModule)getRegisteredModule("server-module");
         if (ShorelineMod.isBaritonePresent()) {
            BARITONE = (BaritoneModule)getRegisteredModule("baritone-module");
         }

         CAPES = (CapesModule)getRegisteredModule("capes-module");
         AURA = (AuraModule)getRegisteredModule("aura-module");
         AUTO_ARMOR = (AutoArmorModule)getRegisteredModule("autoarmor-module");
         AUTO_BOW_RELEASE = (AutoBowReleaseModule)getRegisteredModule("autobowrelease-module");
         AUTO_CRYSTAL = (AutoCrystalModule)getRegisteredModule("autocrystal-module");
         AUTO_LOG = (AutoLogModule)getRegisteredModule("autolog-module");
         AUTO_TOTEM = (AutoTotemModule)getRegisteredModule("autototem-module");
         AUTO_TRAP = (AutoTrapModule)getRegisteredModule("autotrap-module");
         AUTO_WEB = (AutoWebModule)getRegisteredModule("autoweb-module");
         AUTO_XP = (AutoXPModule)getRegisteredModule("autoxp-module");
         BLOCK_LAG = (BlockLagModule)getRegisteredModule("blocklag-module");
         BOW_AIM = (BowAimModule)getRegisteredModule("bowaim-module");
         CLICK_CRYSTAL = (ClickCrystalModule)getRegisteredModule("clickcrystal-module");
         CRITICALS = (CriticalsModule)getRegisteredModule("criticals-module");
         HOLE_FILL = (HoleFillModule)getRegisteredModule("holefill-module");
         NO_HIT_DELAY = (NoHitDelayModule)getRegisteredModule("nohitdelay-module");
         REPLENISH = (ReplenishModule)getRegisteredModule("replenish-module");
         SELF_BOW = (SelfBowModule)getRegisteredModule("selfbow-module");
         SELF_TRAP = (SelfTrapModule)getRegisteredModule("selftrap-module");
         SURROUND = (SurroundModule)getRegisteredModule("surround-module");
         TRIGGER = (TriggerModule)getRegisteredModule("trigger-module");
         ANTI_HUNGER = (AntiHungerModule)getRegisteredModule("antihunger-module");
         CHORUS_CONTROL = (ChorusControlModule)getRegisteredModule("choruscontrol-module");
         CLIENT_SPOOFER = (ClientSpoofModule)getRegisteredModule("clientspoof-module");
         CRASHER = (CrasherModule)getRegisteredModule("crasher-module");
         DISABLER = (DisablerModule)getRegisteredModule("disabler-module");
         EXTENDED_FIREWORK = (ExtendedFireworkModule)getRegisteredModule("extendedfirework-module");
         FAKE_LATENCY = (FakeLatencyModule)getRegisteredModule("fakelatency-module");
         FAST_LATENCY = (FastLatencyModule)getRegisteredModule("fastlatency-module");
         FAST_PROJECTILE = (FastProjectileModule)getRegisteredModule("fastprojectile-module");
         PACKET_CANCELER = (PacketCancelerModule)getRegisteredModule("packetcanceler-module");
         PACKET_FLY = (PacketFlyModule)getRegisteredModule("packetfly-module");
         PHASE = (PhaseModule)getRegisteredModule("phase-module");
         PORTAL_GOD_MODE = (PortalGodModeModule)getRegisteredModule("portalgodmode-module");
         REACH = (ReachModule)getRegisteredModule("reach-module");
         ANTI_AIM = (AntiAimModule)getRegisteredModule("antiaim-module");
         ANTI_SPAM = (AntiSpamModule)getRegisteredModule("antispam-module");
         AUTO_ACCEPT = (AutoAcceptModule)getRegisteredModule("autoaccept-module");
         AUTO_EAT = (AutoEatModule)getRegisteredModule("autoeat-module");
         AUTO_FISH = (AutoFishModule)getRegisteredModule("autofish-module");
         AUTO_RECONNECT = (AutoReconnectModule)getRegisteredModule("autoreconnect-module");
         AUTO_RESPAWN = (AutoRespawnModule)getRegisteredModule("autorespawn-module");
         BEACON_SELECTOR = (BeaconSelectorModule)getRegisteredModule("beaconselector-module");
         BETTER_CHAT = (BetterChatModule)getRegisteredModule("betterchat-module");
         CHAT_NOTIFIER = (ChatNotifierModule)getRegisteredModule("chatnotifier-module");
         CHEST_SWAP = (ChestSwapModule)getRegisteredModule("chestswap-module");
         FAKE_PLAYER = (FakePlayerModule)getRegisteredModule("fakeplayer-module");
         INV_CLEANER = (InvCleanerModule)getRegisteredModule("invcleaner-module");
         MIDDLE_CLICK = (MiddleClickModule)getRegisteredModule("middleclick-module");
         NO_PACKET_KICK = (NoPacketKickModule)getRegisteredModule("nopacketkick-module");
         NO_SOUND_LAG = (NoSoundLagModule)getRegisteredModule("nosoundlag-module");
         PACKET_LOGGER = (PacketLoggerModule)getRegisteredModule("packetlogger-module");
         TIMER = (TimerModule)getRegisteredModule("timer-module");
         TRUE_DURABILITY = (TrueDurabilityModule)getRegisteredModule("truedurability-module");
         UNFOCUSED_FPS = (UnfocusedFPSModule)getRegisteredModule("unfocusedfps-module");
         XCARRY = (XCarryModule)getRegisteredModule("xcarry-module");
         ANTI_LEVITATION = (AntiLevitationModule)getRegisteredModule("antilevitation-module");
         AUTO_WALK = (AutoWalkModule)getRegisteredModule("autowalk-module");
         ELYTRA_FLY = (ElytraFlyModule)getRegisteredModule("elytrafly-module");
         ENTITY_CONTROL = (EntityControlModule)getRegisteredModule("entitycontrol-module");
         ENTITY_SPEED = (EntitySpeedModule)getRegisteredModule("entityspeed-module");
         FAKE_LAG = (FakeLagModule)getRegisteredModule("fakelag-module");
         FAST_FALL = (FastFallModule)getRegisteredModule("fastfall-module");
         FLIGHT = (FlightModule)getRegisteredModule("flight-module");
         ICE_SPEED = (IceSpeedModule)getRegisteredModule("icespeed-module");
         JESUS = (JesusModule)getRegisteredModule("jesus-module");
         LONG_JUMP = (LongJumpModule)getRegisteredModule("longjump-module");
         NO_FALL = (NoFallModule)getRegisteredModule("nofall-module");
         NO_JUMP_DELAY = (NoJumpDelayModule)getRegisteredModule("nojumpdelay-module");
         NO_SLOW = (NoSlowModule)getRegisteredModule("noslow-module");
         PARKOUR = (ParkourModule)getRegisteredModule("parkour-module");
         SPEED = (SpeedModule)getRegisteredModule("speed-module");
         SPRINT = (SprintModule)getRegisteredModule("sprint-module");
         STEP = (StepModule)getRegisteredModule("step-module");
         TICK_SHIFT = (TickShiftModule)getRegisteredModule("tickshift-module");
         TRIDENT_FLY = (TridentFlyModule)getRegisteredModule("tridentfly-module");
         VELOCITY = (VelocityModule)getRegisteredModule("velocity-module");
         YAW = (YawModule)getRegisteredModule("yaw-module");
         BLOCK_HIGHLIGHT = (BlockHighlightModule)getRegisteredModule("blockhighlight-module");
         BREAK_HIGHLIGHT = (BreakHighlightModule)getRegisteredModule("breakhighlight-module");
         CHAMS = (ChamsModule)getRegisteredModule("chams-module");
         ESP = (ESPModule)getRegisteredModule("esp-module");
         EXTRA_TAB = (ExtraTabModule)getRegisteredModule("extratab-module");
         FREECAM = (FreecamModule)getRegisteredModule("freecam-module");
         FULLBRIGHT = (FullbrightModule)getRegisteredModule("fullbright-module");
         HOLE_ESP = (HoleESPModule)getRegisteredModule("holeesp-module");
         NAME_PROTECT = (NameProtectModule)getRegisteredModule("nameprotect-module");
         NAMETAGS = (NametagsModule)getRegisteredModule("nametags-module");
         NO_RENDER = (NoRenderModule)getRegisteredModule("norender-module");
         NO_ROTATE = (NoRotateModule)getRegisteredModule("norotate-module");
         NO_WEATHER = (NoWeatherModule)getRegisteredModule("noweather-module");
         PARTICLES = (ParticlesModule)getRegisteredModule("particles-module");
         PHASE_ESP = (PhaseESPModule)getRegisteredModule("phaseesp-module");
         SKELETON = (SkeletonModule)getRegisteredModule("skeleton-module");
         SKYBOX = (SkyboxModule)getRegisteredModule("skybox-module");
         TOOLTIPS = (TooltipsModule)getRegisteredModule("tooltips-module");
         TRACERS = (TracersModule)getRegisteredModule("tracers-module");
         TRUE_SIGHT = (TrueSightModule)getRegisteredModule("truesight-module");
         VIEW_CLIP = (ViewClipModule)getRegisteredModule("viewclip-module");
         VIEW_MODEL = (ViewModelModule)getRegisteredModule("viewmodel-module");
         ANTI_INTERACT = (AntiInteractModule)getRegisteredModule("antiinteract-module");
         AUTO_MINE = (AutoMineModule)getRegisteredModule("automine-module");
         AUTO_TOOL = (AutoToolModule)getRegisteredModule("autotool-module");
         AVOID = (AvoidModule)getRegisteredModule("avoid-module");
         BLOCK_INTERACT = (BlockInteractModule)getRegisteredModule("blockinteract-module");
         FAST_DROP = (FastDropModule)getRegisteredModule("fastdrop-module");
         FAST_PLACE = (FastPlaceModule)getRegisteredModule("fastplace-module");
         MULTITASK = (MultitaskModule)getRegisteredModule("multitask-module");
         NO_GLITCH_BLOCKS = (NoGlitchBlocksModule)getRegisteredModule("noglitchblocks-module");
         SCAFFOLD = (ScaffoldModule)getRegisteredModule("scaffold-module");
         SPEEDMINE = (SpeedmineModule)getRegisteredModule("speedmine-module");
         initialized = true;
         Iterator var0 = CACHE.iterator();

         while(var0.hasNext()) {
            Module module = (Module)var0.next();
            if (module != null) {
               module.reflectConfigs();
               if (module instanceof ToggleModule) {
                  ToggleModule t = (ToggleModule)module;
                  Managers.MACRO.register(t.getKeybinding());
               }
            }
         }

         CACHE.clear();
      } else {
         throw new RuntimeException("Accessed modules before managers finished initializing!");
      }
   }

   public static boolean isInitialized() {
      return initialized;
   }
}
